// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhVWUTHsxiQp0mJzxOeKenkzh18tNJh18',
    appId: '1:25958846946:web:3197353890e381834129bb',
    messagingSenderId: '25958846946',
    projectId: 'train-transit-backend',
    authDomain: 'train-transit-backend.firebaseapp.com',
    storageBucket: 'train-transit-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhxSNHlJUgcpdiv3M4XrOMy8LVdNPGoys',
    appId: '1:25958846946:android:1be3562f4f22060f4129bb',
    messagingSenderId: '25958846946',
    projectId: 'train-transit-backend',
    storageBucket: 'train-transit-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2nMxZIXpT2NN_SKO1l7ft3gU_7y6Jejw',
    appId: '1:25958846946:ios:df0594595bb8672e4129bb',
    messagingSenderId: '25958846946',
    projectId: 'train-transit-backend',
    storageBucket: 'train-transit-backend.appspot.com',
    iosBundleId: 'com.example.trainTransit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2nMxZIXpT2NN_SKO1l7ft3gU_7y6Jejw',
    appId: '1:25958846946:ios:df0594595bb8672e4129bb',
    messagingSenderId: '25958846946',
    projectId: 'train-transit-backend',
    storageBucket: 'train-transit-backend.appspot.com',
    iosBundleId: 'com.example.trainTransit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhVWUTHsxiQp0mJzxOeKenkzh18tNJh18',
    appId: '1:25958846946:web:26d94e0a7ed06d134129bb',
    messagingSenderId: '25958846946',
    projectId: 'train-transit-backend',
    authDomain: 'train-transit-backend.firebaseapp.com',
    storageBucket: 'train-transit-backend.appspot.com',
  );
}
